services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING:?}
      UPLOAD_PATH: ${UPLOAD_PATH:?}
      JWT_LIFETIME: ${JWT_LIFETIME}
      JWT_ISSUER: ${JWT_ISSUER:?}
      JWT_AUDIENCE: ${JWT_AUDIENCE:?}
      JWT_SECRET: ${JWT_SECRET:?}
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always
    
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api.quiltran.com:/etc/letsencrypt/live/api.quiltran.com
    depends_on:
      - api
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    volumes:
      - ./database_scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always
  
networks:
  app-network: